### 1) What are the main motivations for reducing a dataset’s dimensionality? - 0.5 points
### What are the main drawbacks? - 0.5 points

In [1]:
#motivations
#speed up the training algorithm, visualize the more important features, 
#and save space
#drawbacks
#some information will be lost and may decrease performance
#adds complexity
#computationally intensive 


### Load the MNIST dataset (given below) 


In [2]:
from sklearn.datasets import fetch_openml
mnist = fetch_openml('mnist_784', version=1)
mnist.keys()

dict_keys(['data', 'target', 'frame', 'categories', 'feature_names', 'target_names', 'DESCR', 'details', 'url'])

### 2) Split it into a training set and a test set
### Take the first 60,000 instances for training, and the remaining 10,000 for testing. - 1 point

In [3]:
%%time
X, y = mnist['data'], mnist['target']
print('Shape of X:', X.shape, '\n', 'Shape of y:', y.shape)

Shape of X: (70000, 784) 
 Shape of y: (70000,)
Wall time: 0 ns


In [4]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
%matplotlib inline
y = y.astype(np.uint8)

In [5]:
X_train, X_test, y_train, y_test = X[:60000], X[60000:], y[:60000], y[60000:]
print('Train Data: ', X_train, '\n', 'Test Data:', X_test, '\n',
     'Train label: ', y_train, '\n', 'Test Label: ', y_test)

Train Data:         pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  pixel9  \
0         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
1         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
2         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
3         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
4         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
59995     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
59996     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
59997     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
59998     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
59999     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

       pixel10

### 3) Train a Random Forest classifier on the dataset and time how long it takes, - 1 point
### then evaluate the resulting model on the test set. - 1 point

In [6]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import RandomizedSearchCV, GridSearchCV 
from sklearn.model_selection import cross_val_score


In [7]:
%%time
rf=RandomForestClassifier(n_estimators=100)
rf.fit(X_train,y_train)

Wall time: 36.7 s


RandomForestClassifier()

In [8]:
pred=rf.predict(X_test)
print ("Classification Report")
print(classification_report(y_test, pred))
print ("Confusion Report")
print(confusion_matrix(y_test, pred))

Classification Report
              precision    recall  f1-score   support

           0       0.97      0.99      0.98       980
           1       0.99      0.99      0.99      1135
           2       0.96      0.97      0.96      1032
           3       0.96      0.97      0.96      1010
           4       0.97      0.97      0.97       982
           5       0.97      0.96      0.97       892
           6       0.98      0.98      0.98       958
           7       0.97      0.96      0.97      1028
           8       0.96      0.95      0.96       974
           9       0.95      0.95      0.95      1009

    accuracy                           0.97     10000
   macro avg       0.97      0.97      0.97     10000
weighted avg       0.97      0.97      0.97     10000

Confusion Report
[[ 971    0    1    0    0    1    2    1    3    1]
 [   0 1124    2    2    0    2    2    0    2    1]
 [   6    0  998    8    2    0    2    9    7    0]
 [   0    0    7  976    0    5    0    9  

### 4) Next, use PCA to reduce the dataset’s dimensionality, with an explained variance ratio of 95%. - 2 + 2 points

In [58]:
pca = PCA(n_components=0.95)

In [59]:
from sklearn.preprocessing import StandardScaler
X = StandardScaler().fit_transform(X)

In [60]:
principalComponents = pca.fit_transform(X)

In [62]:
principalDf = pd.DataFrame(data = principalComponents)

In [63]:
principalDf.head(5)

0         1         2         3         4         5          6    \
0 -0.891720 -4.929711 -0.093038 -8.064180 -0.751001  1.051980   0.283377   
1  8.813530 -7.517560 -3.714185 -1.766171  0.891472 -5.107950  -0.134795   
2  2.204835  9.824461 -5.752488  1.479673  4.397900  2.507393  18.927843   
3 -6.534627 -4.029669  3.524017 -0.218098  5.606259  3.493731   1.445046   
4 -5.251618  3.278848 -6.182219  1.462658 -1.667989 -0.580801  -0.565828   

        7         8         9    ...       322       323       324       325  \
0  1.423696 -1.168523  2.406929  ...  0.155843 -0.130359  0.791173  0.168495   
1  3.197223 -0.238224 -1.003382  ... -0.080121  0.143971 -0.075292 -0.054148   
2  3.888938  2.443365 -0.145296  ...  0.333313  0.668359 -1.050376 -0.452535   
3 -4.683887 -0.613930 -2.533648  ... -0.314217 -0.124090 -0.325576 -0.443792   
4 -3.129538  0.005915 -0.972611  ...  0.145473 -0.138217  0.372599  0.129113   

        326       327       328       329       330       331  
0  0.157279 -0.442585 -1.471752  0.301955  0.349144 -0.752368  
1 -0.328657 -0.097342 -0.277915 -0.066247 -0.316840 -0.180312  
2  0.122534  0.702811  1.210336 -1.227017 -0.579337 -0.585607  
3  0.208390  0.067788 -0.004242  0.064486 -0.141908 -0.005184  
4 -0.887090  0.386616  1.051650 -0.171021 -0.359139 -0.719385  

[5 rows x 332 columns]

In [64]:
finalDf = pd.concat([principalDf, y], axis = 1)
finalDf.head(5)

0         1         2         3         4         5          6  \
0 -0.891720 -4.929711 -0.093038 -8.064180 -0.751001  1.051980   0.283377   
1  8.813530 -7.517560 -3.714185 -1.766171  0.891472 -5.107950  -0.134795   
2  2.204835  9.824461 -5.752488  1.479673  4.397900  2.507393  18.927843   
3 -6.534627 -4.029669  3.524017 -0.218098  5.606259  3.493731   1.445046   
4 -5.251618  3.278848 -6.182219  1.462658 -1.667989 -0.580801  -0.565828   

          7         8         9  ...       323       324       325       326  \
0  1.423696 -1.168523  2.406929  ... -0.130359  0.791173  0.168495  0.157279   
1  3.197223 -0.238224 -1.003382  ...  0.143971 -0.075292 -0.054148 -0.328657   
2  3.888938  2.443365 -0.145296  ...  0.668359 -1.050376 -0.452535  0.122534   
3 -4.683887 -0.613930 -2.533648  ... -0.124090 -0.325576 -0.443792  0.208390   
4 -3.129538  0.005915 -0.972611  ... -0.138217  0.372599  0.129113 -0.887090   

        327       328       329       330       331  class  
0 -0.442585 -1.471752  0.301955  0.349144 -0.752368      5  
1 -0.097342 -0.277915 -0.066247 -0.316840 -0.180312      0  
2  0.702811  1.210336 -1.227017 -0.579337 -0.585607      4  
3  0.067788 -0.004242  0.064486 -0.141908 -0.005184      1  
4  0.386616  1.051650 -0.171021 -0.359139 -0.719385      9  

[5 rows x 333 columns]

In [76]:
pca.explained_variance_ratio_

array([0.05642719, 0.04041226, 0.03738273, 0.02893   , 0.02520752,
       0.02192549, 0.01914282, 0.01740684, 0.01532232, 0.01396087,
       0.01342175, 0.01201421, 0.01113962, 0.01090582, 0.01027986,
       0.00994955, 0.00931255, 0.00919635, 0.008886  , 0.00863195,
       0.00821741, 0.00798417, 0.00762573, 0.00742315, 0.0071657 ,
       0.00689314, 0.00681399, 0.00654588, 0.00627293, 0.00610345,
       0.00597261, 0.00589304, 0.00567358, 0.00559358, 0.00552473,
       0.00534443, 0.00527593, 0.00515841, 0.00505498, 0.00477438,
       0.00476312, 0.00465155, 0.00453454, 0.00445757, 0.00442313,
       0.00437877, 0.00437294, 0.00427724, 0.00424808, 0.00418524,
       0.00404059, 0.00396258, 0.00393176, 0.00390562, 0.00386444,
       0.00377501, 0.00373883, 0.00368328, 0.00360377, 0.0035637 ,
       0.00349289, 0.00344527, 0.00343239, 0.00341   , 0.00334463,
       0.00332107, 0.00329803, 0.00319433, 0.0031711 , 0.00315431,
       0.00309941, 0.00305782, 0.00305095, 0.0030396 , 0.00296

In [75]:
np.sum(pca.explained_variance_ratio_)

0.9500311796713781

In [66]:
finalDf.shape


(70000, 333)

In [67]:
X_train, X_test, y_train, y_test = principalDf[:60000], principalDf[60000:], y[:60000], y[60000:]
print('Train Data: ', X_train, '\n', 'Test Data:', X_test, '\n',
     'Train label: ', y_train, '\n', 'Test Label: ', y_test)

Train Data:              0         1         2         3         4         5          6    \
0     -0.891720 -4.929711 -0.093038 -8.064180 -0.751001  1.051980   0.283377   
1      8.813530 -7.517560 -3.714185 -1.766171  0.891472 -5.107950  -0.134795   
2      2.204835  9.824461 -5.752488  1.479673  4.397900  2.507393  18.927843   
3     -6.534627 -4.029669  3.524017 -0.218098  5.606259  3.493731   1.445046   
4     -5.251618  3.278848 -6.182219  1.462658 -1.667989 -0.580801  -0.565828   
...         ...       ...       ...       ...       ...       ...        ...   
59995 -2.007665 -5.225704  0.158207 -4.569564 -0.484836  2.960225  -0.229372   
59996  0.623991 -6.664259  3.325271 -8.348646 -0.806939  1.384817   3.986052   
59997 -3.810553 -3.206503 -3.923271 -7.557723 -1.163991 -2.873995   1.709651   
59998  1.881156 -4.918848 -0.272631  7.077436 -1.012683 -5.130376   3.903368   
59999 -1.324238 -6.128457 -3.236615 -0.304707  3.564504  2.781371  -0.339315   

            7         8   

### 5)  Train a new Random Forest classifier on the reduced dataset and see how long it takes. - 1 point
### Was training much faster? 

In [68]:
%%time
rf=RandomForestClassifier(n_estimators=100)
rf.fit(X_train,y_train)

Wall time: 1min 57s


RandomForestClassifier()

In [69]:
#comparing the two training times, the first clasifier took 36.7 seconds to train 
#while the new classifier took 1min 57s to train increasing computation time significantly

### 6) Next evaluate the classifier on the test set: how does it compare to the previous classifier? - 1 point

In [70]:
pred=rf.predict(X_test)
print ("Classification Report")
print(classification_report(y_test, pred))
print ("Confusion Report")
print(confusion_matrix(y_test, pred))

Classification Report
              precision    recall  f1-score   support

           0       0.96      0.98      0.97       980
           1       0.99      0.98      0.99      1135
           2       0.92      0.92      0.92      1032
           3       0.89      0.93      0.91      1010
           4       0.94      0.95      0.95       982
           5       0.94      0.90      0.92       892
           6       0.95      0.96      0.96       958
           7       0.93      0.92      0.92      1028
           8       0.93      0.92      0.92       974
           9       0.93      0.90      0.92      1009

    accuracy                           0.94     10000
   macro avg       0.94      0.94      0.94     10000
weighted avg       0.94      0.94      0.94     10000

Confusion Report
[[ 958    0    4    3    0    3    8    2    2    0]
 [   0 1116    6    2    2    1    5    0    3    0]
 [  13    0  953   20    4    0    9    9   23    1]
 [   2    0   15  941    1   13    1   17  

In [ ]:
#with the new clacifier precision falls to 94% while on the full dataset the precision was above 97% average