### Question 1

Use the techniques you learned in class to solve this problem.

(a) Zoo Animal Classification data set will be used in this problem. Load the data set from below link.<br>
https://www.kaggle.com/uciml/zoo-animal-classification

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
Data = pd.read_csv("zoo.csv")
DataClasses = pd.read_csv("class.csv")

In [44]:
Data

animal_name  hair  feathers  eggs  milk  airborne  aquatic  predator  \
0      aardvark     1         0     0     1         0        0         1   
1      antelope     1         0     0     1         0        0         0   
2          bass     0         0     1     0         0        1         1   
3          bear     1         0     0     1         0        0         1   
4          boar     1         0     0     1         0        0         1   
..          ...   ...       ...   ...   ...       ...      ...       ...   
96      wallaby     1         0     0     1         0        0         0   
97         wasp     1         0     1     0         1        0         0   
98         wolf     1         0     0     1         0        0         1   
99         worm     0         0     1     0         0        0         0   
100        wren     0         1     1     0         1        0         0   

     toothed  backbone  breathes  venomous  fins  legs  tail  domestic  \
0          1         1         1         0     0     4     0         0   
1          1         1         1         0     0     4     1         0   
2          1         1         0         0     1     0     1         0   
3          1         1         1         0     0     4     0         0   
4          1         1         1         0     0     4     1         0   
..       ...       ...       ...       ...   ...   ...   ...       ...   
96         1         1         1         0     0     2     1         0   
97         0         0         1         1     0     6     0         0   
98         1         1         1         0     0     4     1         0   
99         0         0         1         0     0     0     0         0   
100        0         1         1         0     0     2     1         0   

     catsize  class_type  
0          1           1  
1          1           1  
2          0           4  
3          1           1  
4          1           1  
..       ...         ...  
96         1           1  
97         0           6  
98         1           1  
99         0           7  
100        0           2  

[101 rows x 18 columns]

In [3]:
DataClasses

Class_Number  Number_Of_Animal_Species_In_Class    Class_Type  \
0             1                                 41        Mammal   
1             2                                 20          Bird   
2             3                                  5       Reptile   
3             4                                 13          Fish   
4             5                                  4     Amphibian   
5             6                                  8           Bug   
6             7                                 10  Invertebrate   

                                        Animal_Names  
0  aardvark, antelope, bear, boar, buffalo, calf,...  
1  chicken, crow, dove, duck, flamingo, gull, haw...  
2    pitviper, seasnake, slowworm, tortoise, tuatara  
3  bass, carp, catfish, chub, dogfish, haddock, h...  
4                             frog, frog, newt, toad  
5  flea, gnat, honeybee, housefly, ladybird, moth...  
6  clam, crab, crayfish, lobster, octopus, scorpi...

(b) List target names and feature names of Zoo Animal Classification dataset.

In [4]:
print(Data.keys())
print(Data.animal_name)

Index(['animal_name', 'hair', 'feathers', 'eggs', 'milk', 'airborne',
       'aquatic', 'predator', 'toothed', 'backbone', 'breathes', 'venomous',
       'fins', 'legs', 'tail', 'domestic', 'catsize', 'class_type'],
      dtype='object')
0      aardvark
1      antelope
2          bass
3          bear
4          boar
         ...   
96      wallaby
97         wasp
98         wolf
99         worm
100        wren
Name: animal_name, Length: 101, dtype: object


(c) Split your data using model selection.train test split to 80% training data and 20% test data.

In [5]:
from sklearn import preprocessing

X = Data.iloc[:, 1:-1]
Y = Data.iloc[:, -1]

In [39]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state =5)
print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)

(80, 16)
(21, 16)
(80,)
(21,)


(d)  Use appropriate model and train with the training data set. Test your trained model on the test data set and classify the values of the samples in the test data set.

In [40]:
model = LogisticRegression(max_iter=1000)
model.fit(X_train, Y_train)

LogisticRegression(max_iter=1000)

In [41]:
predictions = model.predict(X_test)
print(predictions)

[7 1 4 1 1 6 1 6 2 1 2 4 2 2 6 1 1 1 2 4 1]


(f) Calculate the accuracy and plot Confusion Matrix.
 <br>

In [45]:
print(accuracy_score(Y_test, predictions))

1.0


In [43]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test, predictions)
print(cm)

[[9 0 0 0 0]
 [0 5 0 0 0]
 [0 0 3 0 0]
 [0 0 0 3 0]
 [0 0 0 0 1]]


(e) Write your comments about the confusion matrix of your experiment.

In [46]:
#since accuracy is 100% confusion matrix is accurate aswell

### Question 2

The handwritten digit data set MNIST is a subset of NIST, which can be used for simple implementation of machine learning algorithms. In this problem, you will use support vector machine to finish the classification of MNIST. <br>
https://www.kaggle.com/c/digit-recognizer/data

(a) Load the first 10K samples from "train.csv" and split them into training and testing data by 0.2. Use sklearn.svm to train a model with raw pixel features. Choose the linear kernel and set C = 5 and gamma= 0.05. Report the model.

In [11]:
DataMnist = pd.read_csv("train.csv", nrows= 10000)
DataMnistTest = pd.read_csv("test.csv")

In [12]:
print(DataMnist.shape)

(10000, 785)


In [13]:
DataMnist.keys()

Index(['label', 'pixel0', 'pixel1', 'pixel2', 'pixel3', 'pixel4', 'pixel5',
       'pixel6', 'pixel7', 'pixel8',
       ...
       'pixel774', 'pixel775', 'pixel776', 'pixel777', 'pixel778', 'pixel779',
       'pixel780', 'pixel781', 'pixel782', 'pixel783'],
      dtype='object', length=785)

In [14]:
x = DataMnist.iloc[:, 1:]
y = DataMnist.iloc[:, 0]

In [15]:
x

pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0          0       0       0       0       0       0       0       0       0   
1          0       0       0       0       0       0       0       0       0   
2          0       0       0       0       0       0       0       0       0   
3          0       0       0       0       0       0       0       0       0   
4          0       0       0       0       0       0       0       0       0   
...      ...     ...     ...     ...     ...     ...     ...     ...     ...   
9995       0       0       0       0       0       0       0       0       0   
9996       0       0       0       0       0       0       0       0       0   
9997       0       0       0       0       0       0       0       0       0   
9998       0       0       0       0       0       0       0       0       0   
9999       0       0       0       0       0       0       0       0       0   

      pixel9  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0          0  ...         0         0         0         0         0         0   
1          0  ...         0         0         0         0         0         0   
2          0  ...         0         0         0         0         0         0   
3          0  ...         0         0         0         0         0         0   
4          0  ...         0         0         0         0         0         0   
...      ...  ...       ...       ...       ...       ...       ...       ...   
9995       0  ...         0         0         0         0         0         0   
9996       0  ...         0         0         0         0         0         0   
9997       0  ...         0         0         0         0         0         0   
9998       0  ...         0         0         0         0         0         0   
9999       0  ...         0         0         0         0         0         0   

      pixel780  pixel781  pixel782  pixel783  
0            0         0         0         0  
1            0         0         0         0  
2            0         0         0         0  
3            0         0         0         0  
4            0         0         0         0  
...        ...       ...       ...       ...  
9995         0         0         0         0  
9996         0         0         0         0  
9997         0         0         0         0  
9998         0         0         0         0  
9999         0         0         0         0  

[10000 rows x 784 columns]

In [16]:
y

0       1
1       0
2       1
3       4
4       0
       ..
9995    5
9996    0
9997    4
9998    7
9999    9
Name: label, Length: 10000, dtype: int64

In [17]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(8000, 784)
(2000, 784)
(8000,)
(2000,)


In [18]:
from sklearn import svm
clf = svm.SVC(kernel='linear', C=5, gamma=.05)
clf.fit(x_train, y_train)
y_pred = clf.predict(x_test)

In [19]:
y_pred

array([4, 4, 0, ..., 9, 6, 7], dtype=int64)

In [20]:
y_test

6580    4
4048    4
21      6
2993    8
3730    6
       ..
3773    5
564     4
5848    9
6160    6
4471    9
Name: label, Length: 2000, dtype: int64

In [21]:
from sklearn import metrics

print("Accuracy", metrics.accuracy_score(y_test, y_pred))

Accuracy 0.9155


In [22]:
print("Precision", metrics.precision_score(y_test, y_pred, average=None))
print("Recall", metrics.recall_score(y_test, y_pred, average=None))

Precision [0.94883721 0.92920354 0.91769547 0.8592233  0.95145631 0.84242424
 0.95604396 0.93925234 0.91823899 0.875     ]
Recall [0.98550725 0.96774194 0.93697479 0.91237113 0.94230769 0.84242424
 0.93548387 0.93055556 0.8021978  0.86096257]


(b) How many support vectors does each class have? List the support vectors for each class and test the prediction accuracy by metrics.classification report.

In [23]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.95      0.99      0.97       207
           1       0.93      0.97      0.95       217
           2       0.92      0.94      0.93       238
           3       0.86      0.91      0.89       194
           4       0.95      0.94      0.95       208
           5       0.84      0.84      0.84       165
           6       0.96      0.94      0.95       186
           7       0.94      0.93      0.93       216
           8       0.92      0.80      0.86       182
           9       0.88      0.86      0.87       187

    accuracy                           0.92      2000
   macro avg       0.91      0.91      0.91      2000
weighted avg       0.92      0.92      0.92      2000



In [24]:
#number of support vectors per class:
clf.n_support_

array([152, 144, 253, 263, 229, 308, 177, 228, 292, 268])

(c) Repeat (a) and (b) with a RBF kernel and the same C and gamma.

In [25]:
clf = svm.SVC(kernel='rbf', C=5, gamma=.05)
clf.fit(x_train, y_train)
y_pred = clf.predict(x_test)

In [26]:
y_pred

array([1, 1, 1, ..., 1, 1, 1], dtype=int64)

In [27]:
y_test

6580    4
4048    4
21      6
2993    8
3730    6
       ..
3773    5
564     4
5848    9
6160    6
4471    9
Name: label, Length: 2000, dtype: int64

In [28]:
print("Accuracy", metrics.accuracy_score(y_test, y_pred))
print("Precision", metrics.precision_score(y_test, y_pred, average=None))
print("Recall", metrics.recall_score(y_test, y_pred, average=None))

Accuracy 0.1085
Precision [0.     0.1085 0.     0.     0.     0.     0.     0.     0.     0.    ]
Recall [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]


C:\Users\X\anaconda3\envs\cmpe257\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [29]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00       207
           1       0.11      1.00      0.20       217
           2       0.00      0.00      0.00       238
           3       0.00      0.00      0.00       194
           4       0.00      0.00      0.00       208
           5       0.00      0.00      0.00       165
           6       0.00      0.00      0.00       186
           7       0.00      0.00      0.00       216
           8       0.00      0.00      0.00       182
           9       0.00      0.00      0.00       187

    accuracy                           0.11      2000
   macro avg       0.01      0.10      0.02      2000
weighted avg       0.01      0.11      0.02      2000



C:\Users\X\anaconda3\envs\cmpe257\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\X\anaconda3\envs\cmpe257\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\X\anaconda3\envs\cmpe257\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [30]:
#number of support vectors per class:
clf.n_support_

array([784, 878, 807, 815, 759, 741, 817, 823, 768, 808])

(d) Compare the two models and comment on the results.

In [31]:
#rbf kernal is not suitable for this clasivication as its accuracy sufferes greatly at 0.116 % 
#while linear kernal achives 0.907 % accuracy which is significantly better
